Repository Holmusk/servant-hmac-auth, pull requests merged in 2018-09, with the labels that each got.

#8 [#2] Implement function that signs Request
  servant-hmac-auth.cabal
  src/Servant/Auth/Hmac.hs
Labels: crypto

#12 [#9] Add signRequest function
  src/Servant/Auth/Hmac.hs
Labels: crypto, http

#13 Add hmacAuthHandler for servant
  servant-hmac-auth.cabal
  src/Servant/Auth/Hmac.hs
Labels: servant

#14 [#4] Implement client middleware
  servant-hmac-auth.cabal
  src/Servant/Auth/Hmac.hs
Labels: http

#15 [#6] Write server part of the example
  README.lhs
  README.md
  servant-hmac-auth.cabal
  src/Servant/Auth/Hmac.hs
Labels: doc, servant

#19 [#4] [#16] Add Servant client and example
  README.md
  servant-hmac-auth.cabal
  src/Servant/Auth/Hmac.hs
Labels: bug, client

#24 [#20] Restructure project
  servant-hmac-auth.cabal
  src/Servant/Auth/Hmac.hs
  src/Servant/Auth/Hmac/Client.hs
  src/Servant/Auth/Hmac/Crypto.hs
  src/Servant/Auth/Hmac/Server.hs
Labels: refactoring

#25 [#21] Improve error messages
  src/Servant/Auth/Hmac/Crypto.hs
  src/Servant/Auth/Hmac/Server.hs
Labels: refactoring

#26 [#22] Fix client bug
  src/Servant/Auth/Hmac/Client.hs
  src/Servant/Auth/Hmac/Crypto.hs
Labels: bug, http

#27 [#23] Sort query strings before converting
  src/Servant/Auth/Hmac/Client.hs
Labels: bug, client
